# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 04:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fhir', '0003_auto_20160926_0351'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignatureType',
            fields=[
                ('coding_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fhir.Coding')),
            ],
            bases=('fhir.coding',),
        ),
        migrations.RemoveField(
            model_name='signature',
            name='type',
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fhir.Period'),
        ),
        migrations.AlterField(
            model_name='address',
            name='postalCode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='type',
            field=models.CharField(blank=True, choices=[('postal', 'period'), ('physical', 'physical'), ('both', 'both')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='use',
            field=models.CharField(blank=True, choices=[('home', 'home'), ('work', 'work'), ('temp', 'temp'), ('old', 'old')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='authorReference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='authorString',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='text',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='contentType',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='creation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='hash',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='langauge',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='title',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='codeableconcept',
            name='text',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='coding',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='coding',
            name='display',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='coding',
            name='system',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coding',
            name='userSelected',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='coding',
            name='version',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contactpoint',
            name='period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fhir.Period'),
        ),
        migrations.AlterField(
            model_name='contactpoint',
            name='rank',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contactpoint',
            name='system',
            field=models.CharField(blank=True, choices=[('phone', 'phone'), ('fax', 'fax'), ('email', 'email'), ('pager', 'pager'), ('other', 'other')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contactpoint',
            name='use',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contactpoint',
            name='value',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='humanname',
            name='period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fhir.Period'),
        ),
        migrations.AlterField(
            model_name='humanname',
            name='text',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='humanname',
            name='use',
            field=models.CharField(blank=True, choices=[('usual', 'usual'), ('official', 'offical'), ('temp', 'temp'), ('nickname', 'nickname'), ('anonymous', 'anonymous'), ('old', 'old'), ('maiden', 'maiden')], max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='identifier',
            name='assigner',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='identifier',
            name='period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fhir.Period'),
        ),
        migrations.AlterField(
            model_name='identifier',
            name='system',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='identifier',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fhir.CodeableConcept'),
        ),
        migrations.AlterField(
            model_name='identifier',
            name='use',
            field=models.CharField(blank=True, choices=[('usual', 'usual'), ('official', 'official'), ('temp', 'temp'), ('secondary', 'secondary')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='identifier',
            name='value',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='period',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='period',
            name='start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quantity',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='quantity',
            name='comparator',
            field=models.CharField(blank=True, choices=[('<', 'less than'), ('<=', 'less than or equal to'), ('>=', 'greater than or equal to'), ('>', 'greater than')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='quantity',
            name='system',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quantity',
            name='unit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='quantity',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='repeattiming',
            name='boundPeriod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fhir.Period'),
        ),
        migrations.AlterField(
            model_name='repeattiming',
            name='boundQuantity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fhir.Quantity'),
        ),
        migrations.AlterField(
            model_name='repeattiming',
            name='boundRange',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fhir.Range'),
        ),
        migrations.AlterField(
            model_name='repeattiming',
            name='boundsType',
            field=models.CharField(blank=True, choices=[('quantity', 'quantity'), ('range', 'range'), ('period', 'period')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='repeattiming',
            name='count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='repeattiming',
            name='duration',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='repeattiming',
            name='durationMax',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='repeattiming',
            name='durationUnits',
            field=models.CharField(blank=True, choices=[('s', 's'), ('min', 'min'), ('h', 'h'), ('d', 'd'), ('wk', 'wk'), ('mo', 'mo'), ('a', 'a')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='repeattiming',
            name='frequency',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='repeattiming',
            name='frequencyMax',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='repeattiming',
            name='period',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='repeattiming',
            name='periodMax',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='repeattiming',
            name='periodUnits',
            field=models.CharField(blank=True, choices=[('s', 's'), ('min', 'min'), ('h', 'h'), ('d', 'd'), ('wk', 'wk'), ('mo', 'mo'), ('a', 'a')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='repeattiming',
            name='when',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sampleddata',
            name='factor',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='sampleddata',
            name='lowerLimit',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='sampleddata',
            name='upperLimit',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='timing',
            name='code',
            field=models.CharField(blank=True, choices=[('QD', 'QD'), ('QOD', 'QOD'), ('Q4D', 'Q4D'), ('Q6D', 'Q6D'), ('BID', 'BID'), ('TID', 'TID'), ('QID', 'QID'), ('AM', 'AM'), ('PM', 'PM')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='timing',
            name='event',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signaturetype',
            name='signature',
            field=models.ManyToManyField(to='fhir.Signature'),
        ),
    ]
